spring.application.name=circuit-breaker-demo

resilience4j.circuitbreaker.instances.jag.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.jag.slidingWindowSize=5
resilience4j.circuitbreaker.instances.jag.failureRateThreshold=50
resilience4j.circuitbreaker.instances.jag.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.jag.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.jag.minimumNumberOfCalls=5
