version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql8-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: harman2
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  springboot-app:
    image: jag-mysql-crud
    container_name: springboot-app-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/harman2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql

volumes:
  mysql_data:
